version: '3.8'
services:
  frontend:
    build: ./roleBasedDashboardApp
    ports:
      - "4200:80"
  backend:
    build:
      context: ./TaskManagementApp
      dockerfile: TaskManagementApp/Dockerfile
    ports:
      - "5000:5000"
