// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementApp.Data;

#nullable disable

namespace TaskManagementApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250220100719_AddReferenceFieldsToTaskofMachine")]
    partial class AddReferenceFieldsToTaskofMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagementApp.Models.ReferencePiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TotalExecutionTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Unique_Code");

                    b.ToTable("ReferencePieces");
                });

            modelBuilder.Entity("TaskManagementApp.Models.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DependenceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.Property<int>("Priorite")
                        .HasColumnType("int");

                    b.Property<int>("ReferencePieceId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TempsExecution")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ReferencePieceId");

                    b.ToTable("Taches");
                });

            modelBuilder.Entity("TaskManagementApp.Models.TachesSelectionnees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSelection")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReferencePieceId")
                        .HasColumnType("int");

                    b.Property<int>("TacheId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReferencePieceId");

                    b.HasIndex("TacheId");

                    b.ToTable("TachesSelectionnees");
                });

            modelBuilder.Entity("TaskManagementApp.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TempsExecution")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskofMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferencePiece")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferencePieceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TempColumn")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("TempsTotal")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TaskofMachines");
                });

            modelBuilder.Entity("TaskManagementApp.Models.Tache", b =>
                {
                    b.HasOne("TaskManagementApp.Models.ReferencePiece", "ReferencePiece")
                        .WithMany("Taches")
                        .HasForeignKey("ReferencePieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferencePiece");
                });

            modelBuilder.Entity("TaskManagementApp.Models.TachesSelectionnees", b =>
                {
                    b.HasOne("TaskManagementApp.Models.ReferencePiece", "ReferencePiece")
                        .WithMany()
                        .HasForeignKey("ReferencePieceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManagementApp.Models.Tache", "Tache")
                        .WithMany("TachesSelectionnees")
                        .HasForeignKey("TacheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferencePiece");

                    b.Navigation("Tache");
                });

            modelBuilder.Entity("TaskManagementApp.Models.ReferencePiece", b =>
                {
                    b.Navigation("Taches");
                });

            modelBuilder.Entity("TaskManagementApp.Models.Tache", b =>
                {
                    b.Navigation("TachesSelectionnees");
                });
#pragma warning restore 612, 618
        }
    }
}
